### ISSUE TITLE
Answer preview slowdown and syntax highlighting

### ISSUE THREAD

**Issue by grimbough** [Bioconductor/legacy.support.bioconductor.org#66] opened 2019-01-31 17:29 UTC
I've been experiencing the slowdown with answer previews previously reported via email and (I think) in #63 

I only experience problems when I'm replying to a post that contains a code block (or there's already an answer containing code), and doing some digging I think it's related to the `prettify.js` script.

When loading the page this script seems to identify any `<pre class="prettyprint">` tags and additionally tags the various code elements for punctuation, keywords etc for syntax highlighting.  However every time the page is updated as an answer preview is generated, it adds a new layer of these tags.  After just a few words you end up pretty deep, and even a short code block has numerous elements that are being edited. 

Below is a screen show taken after I've started writing an answer, but the `<pre class="prettyprint">` code block highlighted is in the original question.

![image](https://user-images.githubusercontent.com/971237/52072206-d6bafc00-2584-11e9-98a5-e7dbdfd603e3.png)

I think this leads to a slowdown, and this disappears when I disable the `prettify.js` script - but of course the highlighting disappears to.  I'm experiencing the issue on Linux Mint with both Chrome and Firefox.

**Comment by lshep** [comment] 2019-01-31 21:10
Thanks for the detailed bug report!  I'll look into asap

**Comment by lshep** [comment] 2019-02-01 13:53
I changed the rendering back to using prism language-r instead of the prettyprint -   can you let me know if this helps with the slow down.   The highlighting won't be as extensive but there should still be some basic implemented by default

**Comment by lshep** [comment] 2019-02-01 17:20
I realized also that when I changed to use prettyprint I may have specified in the wrong place which may have also been the culprit.  If the above fix works I may try adding the prettyprint in a different location to see if it maintains -  
I couldn't reproduce your screenshot nor experience the slowdown so its difficult for me to try and test/debug this directly without your input -  I appreciate your feedback and patience

**Comment by grimbough** [comment] 2019-02-01 20:44
Thanks for looking into it.  I was waiting for a new post to appear that also contained a some code.  There's a few recent comments with the prism highlighting, but there are also prettyprint entries on the page, so I still see the issue there.

I just made a test post myself, and when writing an answer to that I didn't see any performance issues, so I think for me this is definitely something related to the prettyprint/prettify combo.  

Odd that you can't reproduce it, since I experience it across multiple browsers and with all plugins etc turned off, but I'm happy to test again once you've made some more changes.

**Comment by mtmorgan** [comment] 2019-02-01 22:33
It's possible to recreate this locally, with a little effort. Clone this repository, then in a separate directory "support"...

Copy first the biostar then org/bioconductor static files
```
mkdir support
cd support
cp -r ~/a/github/support.bioconductor.org/biostar/static . 
cp -r ~/a/github/support.bioconductor.org/org/bioconductor/static .
```
Then add https://gist.github.com/mtmorgan/da99869a3eb14f80307e879dab508231  prettify.html and viewed it using a local web server like `adsf`
```
ls prettify.html  # there
adsf  # go to localhost:3000/prettify.html in browser
```
prettify.html contains a number of css and js files, but the `<body>` is simple. If I 'inspect' the comment line in the `<pre>` section, and start typing into the 'new answer' dialog, the span nesting starts to occur.

**Comment by grimbough** [comment] 2019-02-01 22:47
I did something similar adding a `prettyprint` div to outside the preview pane in *demo.html* from https://github.com/jmcmanus/pagedown-extra/tree/master/demo 

Feels like this an issue with the JavaScript code & its interaction with however the preview is updated, rather than something specific in the setup of the support site.

**Comment by mtmorgan** [comment] 2019-02-01 23:19
I think updating org/bioconductor/static/lib/pagedown-extra to contain regexpPrecederPatterns.js combinePrefixPatterns.js defs.js prettify.js content of https://github.com/google/code-prettify/tree/master/js-modules and updating the header to include
```
    <script type="text/javascript" src="/static/lib/pagedown-extra/regexpPrecederPatterns.js"></script>
    <script type="text/javascript" src="/static/lib/pagedown-extra/combinePrefixPatterns.js"></script>
    <script type="text/javascript" src="/static/lib/pagedown-extra/defs.js"></script>
    <script type="text/javascript" src="/static/lib/pagedown-extra/prettify.js"></script>
```
makes the nesting go away, but then the 'preview' is not language-specific
```
<pre class="prettyprint prettyprinted"><code class="language-r">library(rhdf5)
x &lt;- c("foo", "bar")</code></pre>
```
I guess because of that prettyprinted class on `<pre>` -- I guess this is some magic from https://github.com/Bioconductor/support.bioconductor.org/blob/master/org/bioconductor/static/biostar.js#L166 but am well out of my depth...

Something about updating only within the `<div id="wmd-preview" ...>` element.

**Comment by grimbough** [comment] 2019-02-04 10:49
I think I have language specific highlighting working at:
https://www.huber.embl.de/users/msmith/pagedown/prettify.html

I inserted `<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>` as suggested on https://github.com/google/code-prettify

and then had to update the line https://github.com/Bioconductor/support.bioconductor.org/blob/cac092a8e92756dee7cba211f0fa12562edc9e38/org/bioconductor/static/biostar.js#L168

to be 

```javascript
editor.hooks.chain("onPreviewRefresh", function() {
    PR.
});
```
I'm still not sure why a `language-r` gets inserted to the static code chunk at the top, but not the preview, so you end up with different background colors, but I'm not experiencing the nesting/slowdown problem with this implementation.

**Comment by lshep** [comment] 2019-02-04 12:03
Thanks @grimbough I'll look at your implementation today and test some things out.  I appreciate your help in debugging this!

**Comment by lshep** [comment] 2019-02-04 12:33
FWIW:  The difference of the static code vs the preview, I think is because the preview is rendered through the javascript interactively but when the code is submitted and entered into the database this is through a python module markdown2 - so there will be some minor differences - but there is a different script that I think controls the static code insertion https://github.com/Bioconductor/support.bioconductor.org/blob/master/biostar/apps/util/html.py#L130

**Comment by lshep** [comment] 2019-02-05 12:32
The fix should be on the active site now.  hopefully you will no longer see the slow down -   older questions that have posted code will still probably experience the slow down unless we 'edit' there code so it get re-rendered with the new class structure -  but this should be all set for incoming posts. 
Please let me know if you continue to see and issue over the next few days with new posts. 

Also - although I tried to add in a version number to allow for automatic reload of the editor I don't think its quite right yet -  You may need to clear the browser history/cache to see the updates.

**Comment by grimbough** [comment] 2019-02-05 12:50
I've only looked at one post so far, but it seems to be working fine for me.  I had to force refresh to get the answer icons etc to load (as in #63) but once I'd done that it all seems great.  Highlighting looks good, preview generates fine, and there's no noticeable lag.  Thanks a lot!

**Comment by lshep** [comment] 2019-02-05 12:52
Thanks Mike!  I'll close this for now but if you see it reappear please reopen - 

I'm working on the auto reload of templates - hopefully will have some fix for that soon

**Closed as completed by lshep** 2019-02-05 12:52 UTC
